#!/bin/bash

source ../scripts/COMPILE_FLAG
echo "*** Install coeos (leto, s_leton cc_leto, coeos) ***" 
echo "See $LOGDIR/ for details of creation."
echo "Creating makefile"
bash Create_All_Makefile.sh > $LOGDIR/coeos_create_All_Makefile.log
echo "Cleaning ..."
make clean reset > $LOGDIR/coeos_reset.log
echo "Compiling ..."
if make > $LOGDIR/coeos_make.log
then
	echo -e "Success installing coeos\n"
	exit 0
else
	echo -e "\nFail to install coeos !\n"
	exit 1
fi




